AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Tenovos Development Starter Kit

Resources:
  DskProxyFunction_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'dsk-proxy-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_'
      Handler: ./src/handlers/proxy.handler
      Runtime: nodejs16.x
      Timeout: 300
      MemorySize: 256
      ReservedConcurrentExecutions: 1
      Role: !GetAtt 'DskRole_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.Arn'
      Events:
        Typescript:
          Type: Api
          Properties:
            Path: /proxy
            Method: any
      Environment:
        Variables:
          CUSTOMER_ID: '_CUSTOMERID_'
          PUBLISHING_ACCOUNT: '_PUBLISHING_ACCOUNT_'
          MODE: "CLOUD"
          CONFIG_BUCKET: !Ref DskConfigBucket_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_
          QUEUE_URL: !GetAtt 'DskQueue_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.QueueUrl'
          ASYNC_LAMBDA: 'dsk-proxyasync-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_'
  DskProxyAsyncFunction_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'dsk-proxyasync-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_'
      Handler: ./src/handlers/proxy-async.handler
      Runtime: nodejs16.x
      Timeout: 300
      MemorySize: 256
      ReservedConcurrentExecutions: 1
      Role: !GetAtt 'DskRole_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.Arn'
      Environment:
        Variables:
          CUSTOMER_ID: '_CUSTOMERID_'
          PUBLISHING_ACCOUNT: '_PUBLISHING_ACCOUNT_'
          MODE: "CLOUD"
          CONFIG_BUCKET: !Ref DskConfigBucket_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_
          QUEUE_URL: !GetAtt 'DskQueue_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.QueueUrl'          
  DskListEventsFunction_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'dsk-listevents-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_'
      Handler: ./src/handlers/list-events.handler
      Runtime: nodejs16.x
      Timeout: 300
      MemorySize: 256
      ReservedConcurrentExecutions: 1
      Role: !GetAtt 'DskRole_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.Arn'
      Events:
        Typescript:
          Type: Api
          Properties:
            Path: /list-events
            Method: any
      Environment:
        Variables:
          MODE: "CLOUD"          
  DskHandlerFunction_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'dsk-handler-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_'
      Handler: ./src/handlers/handler.handler
      Runtime: nodejs16.x
      Timeout: 900
      MemorySize: 256
      ReservedConcurrentExecutions: 0
      Role: !GetAtt 'DskRole_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.Arn'
      Events:
        QueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt 'DskQueue_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.Arn'
            BatchSize: 1
      Environment:
        Variables:
          CUSTOMER_ID: '_CUSTOMERID_'
          PUBLISHING_ACCOUNT: '_PUBLISHING_ACCOUNT_'
          MODE: "CLOUD"
          CONFIG_BUCKET: !Ref DskConfigBucket_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_
  DskMonitorCsvAggFunction_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'dsk-monitorcsvagg-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_'
      Handler: ./src/handlers/monitor-csv-agg.handler
      Runtime: nodejs16.x
      Timeout: 900
      MemorySize: 256
      ReservedConcurrentExecutions: 0
      Role: !GetAtt 'DskRole_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.Arn'
      Events:
        QueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt 'DskQueueCustomCsvAgg_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.Arn'
            BatchSize: 1
      Environment:
        Variables:
          CUSTOMER_ID: '_CUSTOMERID_'
          PUBLISHING_ACCOUNT: '_PUBLISHING_ACCOUNT_'
          MODE: "CLOUD"
          CONFIG_BUCKET: !Ref DskConfigBucket_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_
  DskMonitorCsvIngestFunction_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'dsk-monitorcsvingest-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_'
      Handler: ./src/handlers/monitor-csv-ingest.handler
      Runtime: nodejs16.x
      Timeout: 900
      MemorySize: 256
      ReservedConcurrentExecutions: 0
      Role: !GetAtt 'DskRole_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.Arn'
      Events:
        QueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt 'DskQueueCustomCsvIngest_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.Arn'
            BatchSize: 1
      Environment:
        Variables:
          CUSTOMER_ID: '_CUSTOMERID_'
          PUBLISHING_ACCOUNT: '_PUBLISHING_ACCOUNT_'
          MODE: "CLOUD"
          CONFIG_BUCKET: !Ref DskConfigBucket_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_
  DskQueue_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_:
    Properties:
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 1209600
      QueueName: '_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_'
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 900
      DelaySeconds: 60
    Type: AWS::SQS::Queue
########################################################################################################
#  Custom queue may need to move to nested stack at a later date                                       #
########################################################################################################    
  DskQueueCustomCsvAgg_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_:
    Properties:
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 1209600
      QueueName: 'customcsvagg_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_'
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 900
      DelaySeconds: 900
    Type: AWS::SQS::Queue    
  DskQueueCustomCsvIngest_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_:
    Properties:
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 1209600
      QueueName: 'customcsvingest_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_'
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 900
      DelaySeconds: 0      
    Type: AWS::SQS::Queue     
  DskRole_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
########################################################################################################
#  When it comes time to allow a developer access to the infrastructure created in this template,      #
#  the below can be added to the trust policy manually with the developers specific login information  #
########################################################################################################
#          - Action:                                                                                   #
#              - sts:AssumeRole                                                                        #
#            Effect: Allow                                                                             #
#            Principal:                                                                                #
#              AWS:                                                                                    #
#                - arn:aws:iam::277892082798:user/ian-test@tenovos.com                                 #
########################################################################################################
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - sqs:*            
                Resource: 
                  - !GetAtt 'DskQueue_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.Arn'
                  - !GetAtt 'DskQueueCustomCsvAgg_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.Arn'
                  - !GetAtt 'DskQueueCustomCsvIngest_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.Arn'
              - Action:
                  - logs:*
                Effect: Allow
                Resource: 
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/dsk-handler-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_:*'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/dsk-proxy-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_:*'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/dsk-proxyasync-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_:*'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/dsk-monitorcsvagg-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_:*'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/dsk-monitorcsvingest-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_:*'                  
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/dsk-listevents-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_:*'
              - Effect: Allow
                Action:
                  - lambda:*            
                Resource: 
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:dsk-handler-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_'
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:dsk-proxy-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_'
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:dsk-proxyasync-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_'
              - Effect: Allow
                Action:
                  - s3:*            
                Resource: 
                  - !Sub 'arn:aws:s3:::dsk-config_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_-us-east-1'
                  - !Sub 'arn:aws:s3:::dsk-config_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_-us-east-1/*'
            Version: '2012-10-17'
          PolicyName: dsk-policy-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_
      RoleName: dsk-role-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_
    Type: AWS::IAM::Role
  PolicySQS_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_:
    Properties:
      PolicyDocument:
        Statement:
          - Action: SQS:*
            Effect: Allow
            Principal: '*'
            Resource: !GetAtt 'DskQueue_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.Arn'
        Version: '2012-10-17'
      Queues:
        - !GetAtt 'DskQueue_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.QueueName'
    Type: AWS::SQS::QueuePolicy
########################################################################################################
#  The below queue is not necessarily part of the dsk and can be removed along with notification on    #
#  config bucket                                                                                       #
########################################################################################################
  PolicySQSCustomCsvAgg_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_:
    Properties:
      PolicyDocument:
        Statement:
          - Action: SQS:*
            Effect: Allow
            Principal: '*'
            Resource: !GetAtt 'DskQueueCustomCsvAgg_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.Arn'
        Version: '2012-10-17'
      Queues:
        - !GetAtt 'DskQueueCustomCsvAgg_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.QueueName'
    Type: AWS::SQS::QueuePolicy
  PolicySQSCustomCsvIngest_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_:
    Properties:
      PolicyDocument:
        Statement:
          - Action: SQS:*
            Effect: Allow
            Principal: '*'
            Resource: !GetAtt 'DskQueueCustomCsvIngest_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.Arn'
        Version: '2012-10-17'
      Queues:
        - !GetAtt 'DskQueueCustomCsvIngest_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.QueueName'
    Type: AWS::SQS::QueuePolicy    
  DskConfigBucket_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "dsk-config_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_${AccountId}-us-east-1"
########################################################################################################
#  The below notification is not necessarily required for the starter it and can be removed so         #
#  unnecessary message publishes are avoided (in which case also remove the queue)                     #
########################################################################################################
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt 'DskQueueCustomCsvAgg_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.Arn' 
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: 'manifest.json'
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt 'DskQueueCustomCsvIngest_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_.Arn' 
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: 'manifest-final.csv'                    
  DskDashboard_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_:
    Type: AWS::CloudWatch::Dashboard
    Properties: 
      DashboardName: dsk-dashboard-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_
      DashboardBody: '{"widgets":[{"type":"explorer","x":0,"y":13,"width":24,"height":15,"properties":{"metrics":[{"metricName":"Invocations","resourceType":"AWS::Lambda::Function","stat":"Sum"},{"metricName":"Duration","resourceType":"AWS::Lambda::Function","stat":"Average"},{"metricName":"Errors","resourceType":"AWS::Lambda::Function","stat":"Sum"},{"metricName":"Throttles","resourceType":"AWS::Lambda::Function","stat":"Sum"}],"labels":[{"key":"tnvs:services:delivery:customer-id","value":"_CUSTOMERID_"},{"key":"tnvs:services:delivery:customer-name","value":"_CUSTOMERNAME_"}],"widgetOptions":{"legend":{"position":"bottom"},"view":"timeSeries","stacked":false,"rowsPerPage":50,"widgetsPerRow":2},"period":300,"splitBy":"","region":"us-east-1"}}]}'

########################################################################################################
#  The custom nested stack section is for feature specific infrastructure and code references.         #
########################################################################################################
#  DskCustomNestedStack_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: custom/template.yml
Outputs:
  ApiGatewayUrl:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/proxy"
    Description: "URL created by for use with feature DSK"
  CloudwatchHandlerUrl: 
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fdsk-handler-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_"
    Description: "Quick access to handler logs"
  CloudwatchProxyUrl: 
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fdsk-proxy-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_"
    Description: "Quick access to proxy logs"
  CloudwatchProxyAsyncUrl: 
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fdsk-proxyasync-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_"
    Description: "Quick access to proxy-async logs"
  LambdaHandlerUrl: 
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/lambda/home?region=${AWS::Region}#/functions/dsk-handler-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_"
    Description: "Quick access to handler lambda"
  LambdaProxyUrl: 
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/lambda/home?region=${AWS::Region}#/functions/dsk-proxy-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_"
    Description: "Quick access to proxy lambda"
  LambdaProxyUrl: 
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/lambda/home?region=${AWS::Region}#/functions/dsk-proxyasync-function-_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_"
    Description: "Quick access to proxy-async lambda"
  SqsUrl:
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/sqs/v2/home?region=${AWS::Region}#/queues/https%3A%2F%2Fsqs.${AWS::Region}.amazonaws.com%2F${AWS::AccountId}%2F_CUSTOMERID_-_CUSTOMERNAME_-_DISAMBIGUATOR_"
    Description: "Quick access to queue"
  ConfigBucket:
    Description: 'Bucket created for the DSK to contain configs or for any purpose required by the integration'
    Value: !Ref DskConfigBucket_CUSTOMERID__CUSTOMERNAME__DISAMBIGUATOR_
